### ISSUE TITLE
データベースを使いたい

### ISSUE THREAD

**Issue by kazweda** [kazweda/codespaces-express#2]
https://zenn.dev/komazarari/articles/intro-codespaces

https://mebee.info/2020/04/07/post-8227/

```
version : "3"
services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```

[GitHub Codespaces上でdocker compose upしたい](https://zenn.dev/yuiseki/articles/89b62b1cfdfaf0)
